### PR TITLE
Add labels for backend deletionProtection

### PR DESCRIPTION
**Pull request by TheBigLee**
## Summary

This PR adds new labels to the service broker that should be set on the composite.
Those labels are required on the composite for the backend deletionProtection feature.

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Categorize the PR by setting a good title and adding one of the labels:
  `bug`, `enhancement`, `documentation`, `change`, `breaking`,
  as they show up in the changelog
- [x] Update tests
- [ ] Link this PR to related issues.

### CODE REVIEW

**Comment by zugao** [comment]
> These labels are not necessary on the composites themselves.

I think he wants to patch from composite to each managed object in crossplane. If I am no wrong there's no way to patch from composition to each managed object ?

**Review by zugao — COMMENTED** [review]
My doubt is do we really need 3 labels to manage deletion protection in our webhook? Can we use one label that would indicate directly deletion protection instead the type of XRD?

**Comment by TheBigLee** [comment]
> These labels are not necessary on the composites themselves.

They are. We need to have them on the composite, so we can use P&T to patch them to the managed resources.

**Comment by zugao** [comment]
> All three are required for the backend deletion protection to work. It's usually handled by the runtime to inject it to all managed resources.

I see then this PR looks good then.

**Review by zugao — APPROVED** [review]
LGTM

**Pull request merged**
